declare namespace KeybindingManager {
    let ASCIIKeyboardMap: Readonly<{
        KeyA: "A";
        KeyB: "B";
        KeyC: "C";
        KeyD: "D";
        KeyE: "E";
        KeyF: "F";
        KeyG: "G";
        KeyH: "H";
        KeyI: "I";
        KeyJ: "J";
        KeyK: "K";
        KeyL: "L";
        KeyM: "M";
        KeyN: "N";
        KeyO: "O";
        KeyP: "P";
        KeyQ: "Q";
        KeyR: "R";
        KeyS: "S";
        KeyT: "T";
        KeyU: "U";
        KeyV: "V";
        KeyW: "W";
        KeyX: "X";
        KeyY: "Y";
        KeyZ: "Z";
        Digit0: "0";
        Digit1: "1";
        Digit2: "2";
        Digit3: "3";
        Digit4: "4";
        Digit5: "5";
        Digit6: "6";
        Digit7: "7";
        Digit8: "8";
        Digit9: "9";
        Enter: "Enter";
        Numpad0: "Num0";
        Numpad1: "Num1";
        Numpad2: "Num2";
        Numpad3: "Num3";
        Numpad4: "Num4";
        Numpad5: "Num5";
        Numpad6: "Num6";
        Numpad7: "Num7";
        Numpad8: "Num8";
        Numpad9: "Num9";
        NumpadAdd: "Num +";
        NumpadSubtract: "Num -";
        NumpadMultiply: "Num *";
        NumpadDivide: "Num /";
        NumpadEnter: "Enter";
        NumpadDecimal: "Num .";
        ArrowLeft: "Left";
        ArrowRight: "Right";
        ArrowUp: "Up";
        ArrowDown: "Down";
        Tab: "Tab";
        Escape: "Esc";
        Space: "Space";
        Delete: "Delete";
        Backspace: "Backspace";
        PageUp: "Page Up";
        PageDown: "Page Down";
        Home: "Home";
        End: "End";
        Alt: "Alt";
        Shift: "Shift";
        Control: "Ctrl";
        Backquote: "`";
        Backslash: "\\";
        Quote: "'";
        Period: ".";
        BracketLeft: "[";
        Slash: "/";
        Comma: ",";
        Minus: "-";
        Equal: "=";
        Semicolon: ";";
        BracketRight: "]";
    }>;
    let ModifierSymbols: Readonly<{
        Ctrl: "⌃";
        Shift: "⇧";
        Alt: "⌥";
    }>;
    let ReverseModifierSymbols: Readonly<{
        '\u2303': "Ctrl";
        '\u21E7': "Shift";
        '\u2325': "Alt";
    }>;
    let KeybindManager: any;
}
declare var KeyManager: any;
