declare function AssetsItemNeckRestraintsCollarLeashBeforeDraw(drawData: DynamicDrawingData<AnimationPersistentData>): DynamicBeforeDrawOverrides;
declare function AssetsItemNeckRestraintsChainLeashBeforeDraw(drawData: DynamicDrawingData<AnimationPersistentData>): DynamicBeforeDrawOverrides;
declare function AssetsItemNeckRestraintsChokeChainBeforeDraw(drawData: DynamicDrawingData<AnimationPersistentData>): DynamicBeforeDrawOverrides;
