declare function InventoryItemNeckRestraintsPetPostTxt0Load(): void;
declare function InventoryItemNeckRestraintsPetPostTxt0Draw(): void;
declare function InventoryItemNeckRestraintsPetPostTxt0Click(): void;
declare function InventoryItemNeckRestraintsPetPostTxt0Exit(): void;
declare function AssetsItemNeckRestraintsPetPostAfterDraw(data: DynamicDrawingData): void;
declare function InventoryItemMiscPetPostTxt0Load(): void;
declare function InventoryItemMiscPetPostTxt0Draw(): void;
declare function InventoryItemMiscPetPostTxt0Click(): void;
declare function InventoryItemMiscPetPostTxt0Exit(): void;
declare function AssetsItemMiscPetPostAfterDraw(data: any): void;
