declare function AssetsItemNeckRestraintsCollarLeashBeforeDraw(data: DynamicDrawingData): DynamicBeforeDrawOverrides;
declare function AssetsItemNeckRestraintsChainLeashBeforeDraw(data: DynamicDrawingData): DynamicBeforeDrawOverrides;
