declare function AssetsItemHeadInteractiveVRHeadsetScriptDraw(drawData: DynamicScriptCallbackData<AnimationPersistentData>): void;
declare const AssetsItemHeadInteractiveVRHeadsetBackgrounds: string[];
