name: Generate stubs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  BC_URL: https://gitgud.io/bananarama92/Bondage-College
  BC_BRANCH: literals

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone BC
        run: |
          git clone $BC_URL --depth=1 --branch=$BC_BRANCH
          cd Bondage-College
          echo "BC_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Generate .d.ts
        run: |
          cd Bondage-College/BondageClub
          cp ../../tsconfig.json tsconfig.json

          npm install typescript
          set +e
          npx -p typescript tsc
          set -e

          cp Scripts/Typedef.d.ts dist/Typedef.d.ts
          cp Assets/Female3DCG/Female3DCG_Types.d.ts dist/Female3DCG_Types.d.ts
          rm -rf ../../artifacts
          mv dist ../../artifacts

      - name: Apply patches
        run: |
          for filename in patches/*.patch; do
            [ -e "$filename" ] || continue
            echo "Applying $filename"
            git apply "$filename"
          done

      - name: Push artifacts
        run: |
          git config --global user.name "GitHub Action [bot]"
          git config --local user.email "action@github.com"
          git add artifacts/*
          if [[ $(git ls-files -m) ]]; then
            git status
            git commit -m "CI: Updating stub files" -m "repo: $BC_URL" -m "branch: $BC_BRANCH" -m "commit: $BC_HASH"
            git push
          else
            echo "nothing to commit"
          fi
