name: Generate stubs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  BC_URL: https://gitgud.io/bananarama92/Bondage-College
  BC_BRANCH: typtyptyp

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Clone BC
        run: |
          git clone $BC_URL --depth=1 --branch=$BC_BRANCH
          cd Bondage-College
          echo "BC_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate .d.ts
        run: |
          cd Bondage-College/BondageClub
          npm install
          cp ../../.github/tsconfig.json tsconfig.json

          set +e
          npx -p typescript tsc
          set -e

          cp Scripts/Typedef.d.ts dist/Typedef.d.ts
          cp Assets/Female3DCG/Female3DCG_Types.d.ts dist/Female3DCG_Types.d.ts
          rm -rf ../../bc
          mv dist ../../bc

      - name: List NPM packages
        run: |
          cd Bondage-College/BondageClub
          npm list

      - name: Apply patches
        run: |
          for filename in patches/*.patch; do
            [ -e "$filename" ] || continue
            echo "Applying $filename"
            git apply "$filename"
          done

      - name: Push artifacts
        run: |
          BC_VERSION=$(python get_bc_version.py Bondage-College/BondageClub/index.html)
          git config --global user.name "GitHub Action [bot]"
          git config --local user.email "action@github.com"
          git add bc/*
          rm -rf Bondage-College
          git status
          if [[ "$(git status --porcelain)" ]]; then
            git commit -m "CI: Update stub files: $BC_VERSION" -m "BC Version: $BC_VERSION" -m "Repo: $BC_URL" -m "Branch: \`$BC_BRANCH\`" -m "Commit: \`$BC_HASH\`"
            git push
          else
            echo "nothing to commit"
          fi
