name: Generate stubs

on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository
        required: false
        default: https://gitgud.io/bananarama92/Bondage-College.git
        type: string
      branch:
        description: Branch
        required: false
        default: typtyptyp
        type: string
  pull_request:
    branches:
      - main

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Parse input
        run: |
          case "${{ github.event_name }}" in
            "pull_request")
              echo "REPO_NAME=https://gitgud.io/bananarama92/Bondage-College.git" >> $GITHUB_ENV
              echo "REPO_BRANCH=typtyptyp" >> $GITHUB_ENV
              ;;
            "workflow_dispatch")
              echo "REPO_NAME=${{ inputs.repo }}" >> $GITHUB_ENV
              echo "REPO_BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
              ;;
            *)
              exit 1;;
          esac

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone BC
        run: |
          git clone $REPO_NAME --depth=1 --branch=$REPO_BRANCH
          cd Bondage-College
          echo "BC_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm list

      - name: Generate .d.ts
        run: |
          cd Bondage-College/BondageClub
          cp ../../.github/tsconfig.json tsconfig.json

          npx -p typescript tsc

          cp ../../.github/patch.d.ts dist/patch.d.ts
          cp Scripts/Typedef.d.ts dist/Typedef.d.ts
          cp Scripts/Messages.d.ts dist/Messages.d.ts
          cp Assets/Female3DCG/Female3DCG_Types.d.ts dist/Female3DCG_Types.d.ts
          rm -rf ../../bc
          mv dist ../../bc

      - name: List NPM packages
        run: |
          npm list

      - name: Update BC-data
        run: |
          cd bc_data
          npm install
          node --unhandled-rejections=strict scripts/update_assets --root=bc

      - name: Push artifacts
        run: |
          BC_VERSION=$(python get_bc_version.py Bondage-College/BondageClub/Scripts/Game.js)
          rm -rf Bondage-College

          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bc/*
          git add bc_data/assetVersion.json
          git status
          git commit --allow-empty -m "CI: Update stub files: $BC_VERSION" -m "BC Version: $BC_VERSION" -m "Repo: $REPO_NAME" -m "Branch: \`$REPO_BRANCH\`" -m "Commit: \`$BC_HASH\`"
          git push
