name: Run against downstream

on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository
        required: false
        default: https://gitgud.io/bananarama92/Bondage-College.git
        type: string
      branch:
        description: Branch
        required: false
        default: typtyptyp
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone BC
        run: |
          git clone ${{ inputs.repo }} --depth=1 --branch=${{ inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm list

      - name: Generate .d.ts
        run: |
          cd Bondage-College/BondageClub
          cp ../../.github/tsconfig.json tsconfig.json

          npx -p typescript tsc

          cp ../../.github/patch.d.ts dist/patch.d.ts
          cp Scripts/Typedef.d.ts dist/Typedef.d.ts
          cp Scripts/Messages.d.ts dist/Messages.d.ts
          cp Assets/Female3DCG/Female3DCG_Types.d.ts dist/Female3DCG_Types.d.ts

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: Bondage-College/BondageClub/dist/**/*.d.ts

  ts:
    name: "Run typescript: ${{ matrix.addon[0] }}"
    runs-on: ubuntu-latest
    needs: [generate_artifacts]
    strategy:
      fail-fast: false
      matrix:
        addon:
          - ["MBS", "https://github.com/bananarama92/MBS.git"]
          - ["LSCG", "https://github.com/littlesera/LSCG.git"]
          - ["FBC", "https://gitlab.com/Sidiousious/bce.git"]
          - ["Universal Remote", "https://gitlab.com/Sidiousious/universal-remote.git"]
          - ["BC-Responsive", "https://github.com/dDeepLb/BC-Responsive.git"]
          - ["TTS", "https://gitlab.com/KatKammand/tts.git"]
    steps:
      - uses: actions/checkout@v4

      - run: rm -rf bc

      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: bc

      - name: Install addon
        run: |
          npm install
          cd /tmp
          git clone ${{ matrix.addon[1] }} "${{ matrix.addon[0] }}" --depth=1
          cd "${{ matrix.addon[0] }}"
          npm install
          npm link $GITHUB_WORKSPACE/.
          npm list

      - name: Run TS
        run: |
          cd /tmp/"${{ matrix.addon[0] }}"
          npx -p typescript tsc --noEmit
